id: I98C94252
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T08:33:16.649094'
last_modified: '2022-06-19T08:33:16.649113'
parser: null
source_metadata:
  title: Hagiography of Jam dbyangs mkhyen brtsei dbang po Kun dga bstan pai rgyal
    mtshan (1820–1892); Lamdre Lobshe, vol. nya, title no. 1
  author: kong sprul blo gros mtha yas/
  description: 'Digital version 2.1 {Wylie}; WYLIE COPY of master xml (completed:
    2013-09-09); unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:rdzong sar khams bye'i lnga rig slob gling / sde dge rdzong sar/ (dzkj)
  - Editorial process:Mathias Fermer (mf), kun dga' rdo rje/ (Kathmandu) (kun)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/341
  bases:
    a90c:
      title: Hagiography of Jam dbyangs mkhyen brtsei dbang po Kun dga bstan pai rgyal
        mtshan (1820–1892); Lamdre Lobshe, vol. nya, title no. 1
      order: 1
      base_file: a90c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
